### PR TITLE
SoD: Added option for starting equipment and improved filename detection

### PR DESCRIPTION
**Pull request by Argent77**

### CODE REVIEW

**Comment by FredrikLindgren** [comment]
Thanks! Do you have any more changes planned or should I tag a new release?

**Comment by Argent77** [comment]
That should be all.

**Comment by FredrikLindgren** [comment]
This is totally formal and definitely counts, but do you sign on the line for making your changes here public domain?

**Comment by Argent77** [comment]
Yes, all my contributions to this project can be published under the Public Domain license.

**Pull request merged**
